name: .NET Core Build

on: 
  push:
    branches:
      - "*"
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.1
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test
